### ISSUE TITLE
Lectures using -keepgit

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#110]
Lectures are currently loaded to /opt/static/lectures in the container.    the permissions on that folder are all for root.

```
drwxr-xr-x 1 student student 4096 Aug  9 14:38 .
drwxr-xr-x 1 student student 4096 May 16 00:26 ..
drwxr-xr-x 1 root    root    4096 Aug 11 15:35 .git
-rw-r--r-- 1 root    root     627 Aug  9 14:31 .gitignore
-rw-r--r-- 1 root    root    6277 Aug  9 14:31 README.md
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 aboutOER
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 dataStructures
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 errors
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 eventDrivenProgramming
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 functionalProgramming
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 inputOutput
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 java
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 ooConcepts
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 ooDesign
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 testing
drwxr-xr-x 2 root    root    4096 Aug  9 14:31 tools
```
the user  is student 
```oer-lectures$ whoami
student
```
any attempt to interact with that git repo is met with the following error
```error: cannot open .git/FETCH_HEAD: Permission denied```

I can't su to root because I don't know the password.  I can use git commands prefaced by sudo, but then gitlab issues a permission denied because of public key problems which makes sense.. .my key should not be copied to the container. 

```
oer-lectures$ sudo git pull
The authenticity of host 'gitlab.socs.uoguelph.ca (131.104.48.98)' can't be established.
ECDSA key fingerprint is SHA256:Ti9A66H4o4hKyKh/Gkq6qbeWvqhTaMRFnAGjxbahePs.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'gitlab.socs.uoguelph.ca,131.104.48.98' (ECDSA) to the list of known hosts.
git@gitlab.socs.uoguelph.ca: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.
```
I can use the git repos in the mounted portion of the container because I can open a terminal on my mac to that location and interact with the git repo that way.  

the lectures really need to move.

**Comment by MarshallAsch** [comment]
Is this issue present with all of the folders or just the lectures one?

**Comment by judiMc** [comment]
the ownership issue does not exist in the other repositories as they are in a folder owned by student.  but the git interaction issue for any git commands requiring communication with the server are still a problem.  

```

no changes added to commit (use "git add" and/or "git commit -a")
oer-tutorials$ git pull
git@gitlab.socs.uoguelph.ca: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
oer-tutorials$ 
```
That said, it is much less of an issue for those ones because I can mount the volume on my host system and interact with git that way.

The wiki git doesn't have this problem because it is set up from within the wiki and is using credentials I gave it.

**Comment by MarshallAsch** [comment]
#112 will fix the ownership issue, but to be able to use SSH keys to upload the repository you will need to mount the key file into the container. (this will also apply to the wiki if ssh authentication is used)
