### ISSUE TITLE
Automated builder doesn't stop the docker container it runs

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#111]
I restarted my machine, built the 2430 container using the autobuilder, and several hours later a docker ps showed me that there were 4 containers running.    only one of them was the container I built.

OS/X,  old IMAC running Catalina

**Comment by MarshallAsch** [comment]
Did any of the build attempts fail? 

What containers were running?

As part of the build process the temporary image needs to shut down so the files can be extracted. (there is a bigger issue if the containers restart or if the containers dont stop).

**Comment by MarshallAsch** [comment]
crashed when cloning the git repo failed (due to the git server being down).


This should be fixable by handling that error and cleaning up gracefuily
