### ISSUE TITLE
home directory for student user

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#35]
The home directory for the student user should be /course   or should have an alias to /course in it.

**Comment by MarshallAsch** [comment]
Should the `student` users home directory have this? currently when you run the docker container and drop into an interactive shell the user starts in the `/course` directory.  Do you want this to be added in addition to that?

**Comment by judiMc** [comment]
I think that if a student types cd<return> they should end up in a directory that is either the course directory or one that has the course directory in it.
