### ISSUE TITLE
command prompt default

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#36]
the command prompt on the terminal window is not useful.  Should be changed to some version of current directory.

**Comment by MarshallAsch** [comment]
Im not really sure what this means. is this the PS1 line of the shell? is this the MOTD when the container starts or something else?

**Comment by judiMc** [comment]
this is what the command prompt on the terminal looks like now.  
root@f1c77ea7b715:/course/practiceProblems/errors/calcWithExceptions# 

the "root@asfadaf" is not useful for a student (even if it says "student@).    There are many options for setting that prompt that can shorten it including just outputting the current directory and not the whole tree.

**Comment by MarshallAsch** [comment]
do you have a specific PS1 line that you would like to have?

**Comment by judiMc** [comment]
I commented in the wrong issue damit.    Something that doesn't take up the entire terminal window, lets the user know they aren't on their own machine and helps them know where they are.   I didn't hate this:   PS1="--\W>"

**Comment by MarshallAsch** [comment]
> I commented in the wrong issue damit. 

wrong project too :) , most of these issues are for the https://github.com/sci-oer/oo-resources project

**Comment by MarshallAsch** [comment]
What are your thoughts on this:

<img width="129" alt="image" src="https://user-images.githubusercontent.com/18215471/160247677-653920a9-9b69-4751-b67a-32c716077c22.png">

`PS1="\[\033[01;32m\]oer\[\033[00m\]-\[\033[01;34m\]\W\[\033[00m\]\$ "`

its a slight modification on yours, I am a big fan of colors in my prompts.

**Comment by MarshallAsch** [comment]
added as of [e4e3751](https://github.com/sci-oer/oo-resources/commit/e4e3751c91053a2ed4e4155c9e2648ecdd576128)

**Comment by judiMc** [comment]
> What are your thoughts on this:
> 
> <img alt="image" width="129" src="https://user-images.githubusercontent.com/18215471/160247677-653920a9-9b69-4751-b67a-32c716077c22.png">
> 
> `PS1="\[\033[01;32m\]oer\[\033[00m\]-\[\033[01;34m\]\W\[\033[00m\]\$ "`
> 
> its a slight modification on yours, I am a big fan of colors in my prompts.

perfect.
