### ISSUE TITLE
student proof install/running

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#37]
Need to make instructions for grabbing the container (assuming its been uploaded to the socs dockerhub) and for setting it up to be run from docker desktop.     Instructions need to work on os/x as well as windows.

**Comment by MarshallAsch** [comment]
I like the idea of creating cli wrappers that can be installed  on the host system that act as a wrapper around the docker run command.  Something like a `pip`, `npm`, `homebrew` or native package. 

Something like the following commands:

```
$ sci-oer start [--no-pull] [--no-save] [--path=<path to mount>] [--user=<uid>[:<guid>]] [--background] <image name>

$ sci-oer stop <image>

$ sci-oer shell <image>

$ sci-oer about <image>

$ sci-oer help

$ sci-oer version

```

**Comment by MarshallAsch** [comment]
This is partially going to be implemented through the [sci-oer/student-cli](https://github.com/sci-oer/student-cli) project.

**Comment by MarshallAsch** [comment]
This has been completed in the other repo .
