### ISSUE TITLE
docker desktop "open in browser"

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#38]
if one clicks "open in browser" on docker desktop it goes to port 2222.   Is it possible to change that so it goes to the wiki port?

**Comment by MarshallAsch** [comment]
This is an issue with docker desktop and is not something we can fix. See https://github.com/docker/for-win/issues/9537 for more information

**Comment by judiMc** [comment]
is it possible for us to redirect :2222 to :3000?

**Comment by MarshallAsch** [comment]
I suppose, but I would prefer not too, I personally would find that a lot more confusing with what port goes to what service. 

Do you think it would be a common use case to run the container through docker desktop?

**Comment by judiMc** [comment]
I dunno.  We'll play test it this spring and see if they have any issues.   Maybe we should make a shell script/batch file to run it so that they don't have to cut/paste the command from the readme.    Right now it is sensitive to where you start it from, so if they run the startup command from a directory other than where it was installed, the container happily starts but none of the files are present.     That will be an issue.

**Comment by MarshallAsch** [comment]
> directory other than where it was installed, the container happily starts but none of the files are present. That will be an issue.

This is an inherent limitation of how docker volume mounts work. The only files that will be persisted will be the ones on that mount, as long as the same path is specified every time a fresh container is run. 

We could create a sort of install script and other commands that wrap the container startup that _should_ make that a little bit easier / but that would only do so much

**Comment by judiMc** [comment]
I dunno,  I played around a bit.   I didn't hate this: PS1="--\W>"   Something shorter, tells the user where they are, and gives them a clue that they are on the container.  

Also, I can't see the cursor on the terminal I have running and can't remember if that has always been a thing or if it is just this instance.

**Comment by judiMc** [comment]
hmmm.. ok, I'll think about this.  It might just have to be very very explicit instructions.

**Comment by MarshallAsch** [comment]
Im currently writing documentation for this repository, I think it will make sense to create a usage / documentation / support website for this project as well. I think it will help with that as well given that the goal of this project is not for a single course
