### ISSUE TITLE
additional content

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#40]
in addition to the wiki and the jupyter tutorials there is a set of practice problems  that go, predictably, in the /course/practiceProblem folder.    There will also be a set of video lectures that go in the /course/lectures folder

**Comment by MarshallAsch** [comment]
where would this content get loaded from?

**Comment by judiMc** [comment]
practiceProblems will be in a git repo.    videoLectures could be as well.  

I could stuff all of the content excluding the wiki into the same git repo with different subdirectories if that made more sense?

**Comment by MarshallAsch** [comment]
done as of 7f76d7a

**Comment by MarshallAsch** [comment]
this is a duplicate of #14
